# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas-docs.github.io/pandas-docs-travis/io.html#json
+ data source: http://jsonstudio.com/resources/
****

In [1]:
import pandas as pd

## imports for Python, Pandas

In [2]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas-docs.github.io/pandas-docs-travis/io.html#normalization

In [4]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [7]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

         name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [8]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

         name  population info.governor    state shortname
0        Dade       12345    Rick Scott  Florida        FL
1     Broward       40000    Rick Scott  Florida        FL
2  Palm Beach       60000    Rick Scott  Florida        FL
3      Summit        1234   John Kasich     Ohio        OH
4    Cuyahoga        1337   John Kasich     Ohio        OH

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [3]:
# load json as string
json.load((open('data/world_bank_projects_less.json')))

[{u'_id': {u'$oid': u'52b213b38594d8a2be17c780'},
  u'approvalfy': 1999,
  u'board_approval_month': u'November',
  u'boardapprovaldate': u'2013-11-12T00:00:00Z',
  u'borrower': u'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA',
  u'closingdate': u'2018-07-07T00:00:00Z',
  u'country_namecode': u'Federal Democratic Republic of Ethiopia!$!ET',
  u'countrycode': u'ET',
  u'countryname': u'Federal Democratic Republic of Ethiopia',
  u'countryshortname': u'Ethiopia',
  u'docty': u'Project Information Document,Indigenous Peoples Plan,Project Information Document',
  u'envassesmentcategorycode': u'C',
  u'grantamt': 0,
  u'ibrdcommamt': 0,
  u'id': u'P129828',
  u'idacommamt': 130000000,
  u'impagency': u'MINISTRY OF EDUCATION',
  u'lendinginstr': u'Investment Project Financing',
  u'lendinginstrtype': u'IN',
  u'lendprojectcost': 550000000,
  u'majorsector_percent': [{u'Name': u'Education', u'Percent': 46},
   {u'Name': u'Education', u'Percent': 26},
   {u'Name': u'Public Administration, Law, and Justice', u'Percent': 16},
   {u'Name': u'Education', u'Percent': 12}],
  u'mjsector_namecode': [{u'code': u'EX', u'name': u'Education'},
   {u'code': u'EX', u'name': u'Education'},
   {u'code': u'BX', u'name': u'Public Administration, Law, and Justice'},
   {u'code': u'EX', u'name': u'Education'}],
  u'mjtheme': [u'Human development'],
  u'mjtheme_namecode': [{u'code': u'8', u'name': u'Human development'},
   {u'code': u'11', u'name': u''}],
  u'mjthemecode': u'8,11',
  u'prodline': u'PE',
  u'prodlinetext': u'IBRD/IDA',
  u'productlinetype': u'L',
  u'project_abstract': {u'cdata': u'The development objective of the Second Phase of General Education Quality Improvement Project for Ethiopia is to improve learning conditions in primary and secondary schools and strengthen institutions at different levels of educational administration. The project has six components. The first component is curriculum, textbooks, assessment, examinations, and inspection. This component will support improvement of learning conditions in grades KG-12 by providing increased access to teaching and learning materials and through improvements to the curriculum by assessing the strengths and weaknesses of the current curriculum. This component has following four sub-components: (i) curriculum reform and implementation; (ii) teaching and learning materials; (iii) assessment and examinations; and (iv) inspection. The second component is teacher development program (TDP). This component will support improvements in learning conditions in both primary and secondary schools by advancing the quality of teaching in general education through: (a) enhancing the training of pre-service teachers in teacher education institutions; and (b) improving the quality of in-service teacher training. This component has following three sub-components: (i) pre-service teacher training; (ii) in-service teacher training; and (iii) licensing and relicensing of teachers and school leaders. The third component is school improvement plan. This component will support the strengthening of school planning in order to improve learning outcomes, and to partly fund the school improvement plans through school grants. It has following two sub-components: (i) school improvement plan; and (ii) school grants. The fourth component is management and capacity building, including education management information systems (EMIS). This component will support management and capacity building aspect of the project. This component has following three sub-components: (i) capacity building for education planning and management; (ii) capacity building for school planning and management; and (iii) EMIS. The fifth component is improving the quality of learning and teaching in secondary schools and universities through the use of information and communications technology (ICT). It has following five sub-components: (i) national policy and institution for ICT in general education; (ii) national ICT infrastructure improvement plan for general education; (iii) develop an integrated monitoring, evaluation, and learning system specifically for the ICT component; (iv) teacher professional development in the use of ICT; and (v) provision of limited number of e-Braille display readers with the possibility to scale up to all secondary education schools based on the successful implementation and usage of the readers. The sixth component is program coordination, monitoring and evaluation, and communication. It will support institutional strengthening by developing capacities in all aspects of program coordination, monitoring and evaluation; a new sub-component on communications will support information sharing for better management and accountability. It has following three sub-components: (i) program coordination; (ii) monitoring and evaluation (M and E); and (iii) communication.'},
  u'project_name': u'Ethiopia General Education Quality Improvement Project II',
  u'projectdocs': [{u'DocDate': u'28-AUG-2013',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b081e545fb_1_0',
    u'EntityID': u'090224b081e545fb_1_0'},
   {u'DocDate': u'01-JUL-2013',
    u'DocType': u'IP',
    u'DocTypeDesc': u'Indigenous Peoples Plan (IP),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20130920111729',
    u'EntityID': u'000442464_20130920111729'},
   {u'DocDate': u'22-NOV-2012',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b0817b19e2_1_0',
    u'EntityID': u'090224b0817b19e2_1_0'}],
  u'projectfinancialtype': u'IDA',
  u'projectstatusdisplay': u'Active',
  u'regionname': u'Africa',
  u'sector': [{u'Name': u'Primary education'},
   {u'Name': u'Secondary education'},
   {u'Name': u'Public administration- Other social services'},
   {u'Name': u'Tertiary education'}],
  u'sector1': {u'Name': u'Primary education', u'Percent': 46},
  u'sector2': {u'Name': u'Secondary education', u'Percent': 26},
  u'sector3': {u'Name': u'Public administration- Other social services',
   u'Percent': 16},
  u'sector4': {u'Name': u'Tertiary education', u'Percent': 12},
  u'sector_namecode': [{u'code': u'EP', u'name': u'Primary education'},
   {u'code': u'ES', u'name': u'Secondary education'},
   {u'code': u'BS', u'name': u'Public administration- Other social services'},
   {u'code': u'ET', u'name': u'Tertiary education'}],
  u'sectorcode': u'ET,BS,ES,EP',
  u'source': u'IBRD',
  u'status': u'Active',
  u'supplementprojectflg': u'N',
  u'theme1': {u'Name': u'Education for all', u'Percent': 100},
  u'theme_namecode': [{u'code': u'65', u'name': u'Education for all'}],
  u'themecode': u'65',
  u'totalamt': 130000000,
  u'totalcommamt': 130000000,
  u'url': u'http://www.worldbank.org/projects/P129828/ethiopia-general-education-quality-improvement-project-ii?lang=en'},
 {u'_id': {u'$oid': u'52b213b38594d8a2be17c781'},
  u'approvalfy': 2015,
  u'board_approval_month': u'November',
  u'boardapprovaldate': u'2013-11-04T00:00:00Z',
  u'borrower': u'GOVERNMENT OF TUNISIA',
  u'country_namecode': u'Republic of Tunisia!$!TN',
  u'countrycode': u'TN',
  u'countryname': u'Republic of Tunisia',
  u'countryshortname': u'Tunisia',
  u'docty': u'Project Information Document,Integrated Safeguards Data Sheet,Integrated Safeguards Data Sheet,Project Information Document,Integrated Safeguards Data Sheet,Project Information Document',
  u'envassesmentcategorycode': u'C',
  u'grantamt': 4700000,
  u'ibrdcommamt': 0,
  u'id': u'P144674',
  u'idacommamt': 0,
  u'impagency': u'MINISTRY OF FINANCE',
  u'lendinginstr': u'Specific Investment Loan',
  u'lendinginstrtype': u'IN',
  u'lendprojectcost': 5700000,
  u'majorsector_percent': [{u'Name': u'Public Administration, Law, and Justice',
    u'Percent': 70},
   {u'Name': u'Public Administration, Law, and Justice', u'Percent': 30}],
  u'mjsector_namecode': [{u'code': u'BX',
    u'name': u'Public Administration, Law, and Justice'},
   {u'code': u'BX', u'name': u'Public Administration, Law, and Justice'}],
  u'mjtheme': [u'Economic management',
   u'Social protection and risk management'],
  u'mjtheme_namecode': [{u'code': u'1', u'name': u'Economic management'},
   {u'code': u'6', u'name': u'Social protection and risk management'}],
  u'mjthemecode': u'1,6',
  u'prodline': u'RE',
  u'prodlinetext': u'Recipient Executed Activities',
  u'productlinetype': u'L',
  u'project_name': u'TN: DTF Social Protection Reforms Support',
  u'projectdocs': [{u'DocDate': u'29-MAR-2013',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131024115616',
    u'EntityID': u'000333037_20131024115616'},
   {u'DocDate': u'29-MAR-2013',
    u'DocType': u'ISDS',
    u'DocTypeDesc': u'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20131024151611',
    u'EntityID': u'000356161_20131024151611'},
   {u'DocDate': u'29-MAR-2013',
    u'DocType': u'ISDS',
    u'DocTypeDesc': u'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20131031112136',
    u'EntityID': u'000442464_20131031112136'},
   {u'DocDate': u'29-MAR-2013',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131031105716',
    u'EntityID': u'000333037_20131031105716'},
   {u'DocDate': u'16-JAN-2013',
    u'DocType': u'ISDS',
    u'DocTypeDesc': u'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113209',
    u'EntityID': u'000356161_20130305113209'},
   {u'DocDate': u'16-JAN-2013',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113716',
    u'EntityID': u'000356161_20130305113716'}],
  u'projectfinancialtype': u'OTHER',
  u'projectstatusdisplay': u'Active',
  u'regionname': u'Middle East and North Africa',
  u'sector': [{u'Name': u'Public administration- Other social services'},
   {u'Name': u'General public administration sector'}],
  u'sector1': {u'Name': u'Public administration- Other social services',
   u'Percent': 70},
  u'sector2': {u'Name': u'General public administration sector',
   u'Percent': 30},
  u'sector_namecode': [{u'code': u'BS',
    u'name': u'Public administration- Other social services'},
   {u'code': u'BZ', u'name': u'General public administration sector'}],
  u'sectorcode': u'BZ,BS',
  u'source': u'IBRD',
  u'status': u'Active',
  u'supplementprojectflg': u'N',
  u'theme1': {u'Name': u'Other economic management', u'Percent': 30},
  u'theme_namecode': [{u'code': u'24', u'name': u'Other economic management'},
   {u'code': u'54', u'name': u'Social safety nets'}],
  u'themecode': u'54,24',
  u'totalamt': 0,
  u'totalcommamt': 4700000,
  u'url': u'http://www.worldbank.org/projects/P144674?lang=en'}]

In [10]:
# load as Pandas dataframe
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{u'$oid': u'52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{u'Percent': 100, u'Name': u'Education for all'}","[{u'code': u'65', u'name': u'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{u'$oid': u'52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{u'Percent': 30, u'Name': u'Other economic man...","[{u'code': u'24', u'name': u'Other economic ma...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [4]:
wbpj=pd.read_json('data/world_bank_projects.json')

In [5]:
wbpj.head()

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{u'$oid': u'52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{u'Percent': 100, u'Name': u'Education for all'}","[{u'code': u'65', u'name': u'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{u'$oid': u'52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{u'Percent': 30, u'Name': u'Other economic man...","[{u'code': u'24', u'name': u'Other economic ma...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{u'$oid': u'52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,...,TI,IBRD,Active,Y,"{u'Percent': 46, u'Name': u'Regional integrati...","[{u'code': u'47', u'name': u'Regional integrat...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,{u'$oid': u'52b213b38594d8a2be17c783'},2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of",...,JB,IBRD,Active,N,"{u'Percent': 50, u'Name': u'Participation and ...","[{u'code': u'57', u'name': u'Participation and...","59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,{u'$oid': u'52b213b38594d8a2be17c784'},2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,...,"FH,YW,YZ",IBRD,Active,N,"{u'Percent': 30, u'Name': u'Export development...","[{u'code': u'45', u'name': u'Export developmen...","41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/seco...

In [8]:
wbpj.columns

Index([                     u'_id',               u'approvalfy',
           u'board_approval_month',        u'boardapprovaldate',
                       u'borrower',              u'closingdate',
               u'country_namecode',              u'countrycode',
                    u'countryname',         u'countryshortname',
                          u'docty', u'envassesmentcategorycode',
                       u'grantamt',              u'ibrdcommamt',
                             u'id',               u'idacommamt',
                      u'impagency',             u'lendinginstr',
               u'lendinginstrtype',          u'lendprojectcost',
            u'majorsector_percent',        u'mjsector_namecode',
                        u'mjtheme',         u'mjtheme_namecode',
                    u'mjthemecode',                 u'prodline',
                   u'prodlinetext',          u'productlinetype',
               u'project_abstract',             u'project_name',
                    u'projectdocs',     u'projectfinancialtype',
           u'projectstatusdisplay',               u'regionname',
                         u'sector',                  u'sector1',
                        u'sector2',                  u'sector3',
                        u'sector4',          u'sector_namecode',
                     u'sectorcode',                   u'source',
                         u'status',     u'supplementprojectflg',
                         u'theme1',           u'theme_namecode',
                      u'themecode',                 u'totalamt',
                   u'totalcommamt',                      u'url'],
      dtype='object')

 **10 countries with most projects**

In [9]:
wbpj.countryname.value_counts().head(10)

People's Republic of China         19
Republic of Indonesia              19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
Kingdom of Morocco                 12
People's Republic of Bangladesh    12
Nepal                              12
Republic of Mozambique             11
Africa                             11
dtype: int64

In [115]:
cols=wbpj[['countryname','mjtheme','mjthemecode','mjtheme_namecode']]
cols.sort('countryname')

,countryname,mjtheme,mjthemecode,mjtheme_namecode
167,Africa,"[Trade and integration, Financial and private ...","5,4,4,5","[{u'code': u'5', u'name': u'Trade and integrat..."
449,Africa,"[Urban development, Environment and natural re...","9,11,10,5","[{u'code': u'9', u'name': u'Urban development'..."
99,Africa,"[Trade and integration, Trade and integration,...","5,5,2,10","[{u'code': u'5', u'name': u'Trade and integrat..."
65,Africa,"[Financial and private sector development, Soc...","4,7,10,5","[{u'code': u'4', u'name': u'Financial and priv..."
45,Africa,[Human development],"8,10","[{u'code': u'8', u'name': u'Human development'..."
46,Africa,"[Public sector governance, Rural development, ...","2,10,4,4","[{u'code': u'2', u'name': u'Public sector gove..."
58,Africa,"[Environment and natural resources management,...","11,11","[{u'code': u'11', u'name': u'Environment and n..."
184,Africa,"[Trade and integration, Trade and integration,...","5,5,9,8","[{u'code': u'5', u'name': u'Trade and integrat..."
287,Africa,"[Rural development, Trade and integration, Tra...","10,5,5","[{u'code': u'10', u'name': u'Rural development..."
51,Africa,"[Environment and natural resources management,...","11,11,11,11,11","[{u'code': u'11', u'name': u'Environment and n..."
353,Africa,"[Environment and natural resources management,...","11,7,11","[{u'code': u'11', u'name': u'Environment and n..."
151,Antigua and Barbuda,"[Social protection and risk management, Social...","6,6,6,2","[{u'code': u'6', u'name': u'Social protection ..."
101,Arab Republic of Egypt,[Financial and private sector development],"4,10","[{u'code': u'4', u'name': u'Financial and priv..."
368,Arab Republic of Egypt,"[Human development, Social dev/gender/inclusion]","8,7","[{u'code': u'8', u'name': u'Human development'..."
38,Argentine Republic,"[Environment and natural resources management,...","11,11,6,11,11","[{u'code': u'11', u'name': u'Environment and n..."
72,Argentine Republic,[Environment and natural resources management],"11,4","[{u'code': u'11', u'name': u'Environment and n..."
430,Bosnia and Herzegovina,"[Social dev/gender/inclusion, Environment and ...","7,11,3","[{u'code': u'7', u'name': u'Social dev/gender/..."
191,Burkina Faso,"[Financial and private sector development, Tra...","4,5","[{u'code': u'4', u'name': u'Financial and priv..."
331,Burkina Faso,[Rural development],"10,8","[{u'code': u'10', u'name': u'Rural development..."
360,Burkina Faso,"[Environment and natural resources management,...","11,7,2,7,10","[{u'code': u'11', u'name': u'Environment and n..."
310,Burkina Faso,"[Rural development, Rural development]","10,10","[{u'code': u'10', u'name': u'Rural development..."
441,Burkina Faso,"[Human development, Environment and natural re...","8,11","[{u'code': u'8', u'name': u'Human development'..."
361,Burkina Faso,"[Social dev/gender/inclusion, Rural developmen...","7,10,11","[{u'code': u'7', u'name': u'Social dev/gender/..."
274,Burkina Faso,"[Public sector governance, Financial and priva...","2,4,10,2,8","[{u'code': u'2', u'name': u'Public sector gove..."
71,Burkina Faso,"[Financial and private sector development, Urb...","4,9,10","[{u'code': u'4', u'name': u'Financial and priv..."
180,Burkina Faso,"[Social protection and risk management, Human ...","6,8","[{u'code': u'6', u'name': u'Social protection ..."
366,Central African Republic,[Public sector governance],"2,7","[{u'code': u'2', u'name': u'Public sector gove..."
159,Democratic Republic of Sao Tome and Prin,"[Economic management, Financial and private se...","1,4,2,10,1","[{u'code': u'1', u'name': u'Economic managemen..."
43,Democratic Republic of Sao Tome and Prin,[Public sector governance],"2,8","[{u'code': u'2', u'name': u'Public sector gove..."
324,Democratic Republic of Timor-Leste,"[Human development, Public sector governance]","8,2","[{u'code': u'8', u'name': u'Human development'..."
...,...,...,...,...
241,The Independent State of Papua New Guine,[Human development],"8,11","[{u'code': u'8', u'name': u'Human development'..."
312,The Independent State of Papua New Guine,"[Environment and natural resources management,...","11,4,10","[{u'code': u'11', u'name': u'Environment and n..."
311,The Independent State of Papua New Guine,"[Financial and private sector development, Rur...","4,10","[{u'code': u'4', u'name': u'Financial and priv..."
489,The Independent State of Papua New Guine,"[Urban development, Social protection and risk...","9,6,6,9","[{u'code': u'9', u'name': u'Urban development'..."
2,Tuvalu,"[Trade and integration, Public sector governan...","5,2,11,6","[{u'code': u'5', u'name': u'Trade and integrat..."
47,Ukraine,[Environment and natural resources management],"11,11","[{u'code': u'11', u'name': u'Environment and n..."
414,Ukraine,[Environment and natural resources management],"11,6","[{u'code': u'11', u'name': u'Environment and n..."
363,Ukraine,[Economic management],"1,8","[{u'code': u'1', u'name': u'Economic managemen..."
468,Ukraine,"[Trade and integration, Financial and private ...","5,4","[{u'code': u'5', u'name': u'Trade and integrat..."
384,Union of the Comoros,"[Social protection and risk management, Public...","6,2,2,2,2","[{u'code': u'6', u'name': u'Social protection ..."
257,Union of the Comoros,"[Social dev/gender/inclusion, Rural developmen...","7,10,10,6","[{u'code': u'7', u'name': u'Social dev/gender/..."
48,Union of the Comoros,"[Financial and private sector development, Fin...","4,4","[{u'code': u'4', u'name': u'Financial and priv..."
399,United Mexican States,"[Rural development, Environment and natural re...","10,11","[{u'code': u'10', u'name': u'Rural development..."
487,United Mexican States,"[Environment and natural resources management,...","11,10,10,11","[{u'code': u'11', u'name': u'Environment and n..."
437,United Republic of Tanzania,"[Rural development, Rural development]","10,10","[{u'code': u'10', u'name': u'Rural development..."
271,United Republic of Tanzania,"[Public sector governance, Financial and priva...","2,4,4","[{u'code': u'2', u'name': u'Public sector gove..."
265,United Republic of Tanzania,"[Financial and private sector development, Tra...","4,5,2,1,2","[{u'code': u'4', u'name': u'Financial and priv..."
438,United Republic of Tanzania,"[Rural development, Financial and private sect...","10,4,8,10,10","[{u'code': u'10', u'name': u'Rural development..."
31,United Republic of Tanzania,"[Environment and natural resources management,...","11,11,11,11","[{u'code': u'11', u'name': u'Environment and n..."
432,United Republic of Tanzania,"[Urban development, Public sector governance]","9,2","[{u'code': u'9', u'name': u'Urban development'..."
268,United Republic of Tanzania,"[Financial and private sector development, Soc...","4,7,11,11,4","[{u'code': u'4', u'name': u'Financial and priv..."
346,United Republic of Tanzania,[Public sector governance],"2,1","[{u'code': u'2', u'name': u'Public sector gove..."
178,West Bank and Gaza,"[Human development, Social protection and risk...","8,6,2,2,2","[{u'code': u'8', u'name': u'Human development'..."
389,West Bank and Gaza,"[Financial and private sector development, Urb...","4,9","[{u'code': u'4', u'name': u'Financial and priv..."
177,West Bank and Gaza,"[Social dev/gender/inclusion, Environment and ...","7,11,9,9","[{u'code': u'7', u'name': u'Social dev/gender/..."
69,West Bank and Gaza,"[Social dev/gender/inclusion, Social protectio...","7,6","[{u'code': u'7', u'name': u'Social dev/gender/..."
37,West Bank and Gaza,[Social protection and risk management],"6,7","[{u'code': u'6', u'name': u'Social protection ..."
491,West Bank and Gaza,[Rural development],"10,11","[{u'code': u'10', u'name': u'Rural development..."
55,World,"[Environment and natural resources management,...","11,7,11,11,11","[{u'code': u'11', u'name': u'Environment and n..."
238,World,"[Rural development, Human development]","10,8","[{u'code': u'10', u'name': u'Rural development..."

In [12]:
data=json.load((open('data/world_bank_projects.json')))

In [54]:
import numpy as np

In [156]:
mj=json_normalize(data,'mjtheme_namecode','countryname').sort('code')
mj=mj.replace( '',np.nan, regex=True)
mj.head(10)

     code                 name                  countryname
249     1  Economic management          Republic of Armenia
222     1  Economic management  Hashemite Kingdom of Jordan
2       1  Economic management          Republic of Tunisia
220     1  Economic management          Republic of Tunisia
1260    1  Economic management  Hashemite Kingdom of Jordan
1257    1  Economic management         Republic of Maldives
212     1                  NaN          Republic of Liberia
205     1  Economic management              Kyrgyz Republic
204     1  Economic management              Kyrgyz Republic
357     1  Economic management           Republic of Poland

In [162]:
mjg=mj.groupby(["code"])['name'].transform(lambda s: s.loc[s.first_valid_index()])
mjg=pd.DataFrame(mjg)
mjg.head(10)

                     name
249   Economic management
222   Economic management
2     Economic management
220   Economic management
1260  Economic management
1257  Economic management
212   Economic management
205   Economic management
204   Economic management
357   Economic management

In [178]:
mjc=mj.drop(mj.columns[1],axis=1)
mjc
mjt=mjc.join(mjg)
mjt
mjt.drop_duplicates()

     code                               countryname                 name
249     1                       Republic of Armenia  Economic management
222     1               Hashemite Kingdom of Jordan  Economic management
2       1                       Republic of Tunisia  Economic management
1257    1                      Republic of Maldives  Economic management
212     1                       Republic of Liberia  Economic management
205     1                           Kyrgyz Republic  Economic management
357     1                        Republic of Poland  Economic management
1235    1              Oriental Republic of Uruguay  Economic management
841     1             Socialist Republic of Vietnam  Economic management
363     1                 Republic of Cote d'Ivoire  Economic management
1230    1                      Republic of Colombia  Economic management
1218    1                          Kingdom of Tonga  Economic management
1212    1                         Republic of Kenya  Economic management
1206    1                           Pacific Islands  Economic management
175     1              Islamic State of Afghanistan  Economic management
453     1                        Kingdom of Lesotho  Economic management
454     1  Democratic Republic of Sao Tome and Prin  Economic management
900     1                         Republic of Yemen  Economic management
803     1                        Republic of Panama  Economic management
497     1                        Republic of Malawi  Economic management
1114    1                      Republic of Honduras  Economic management
1078    1                                   Ukraine  Economic management
1057    1                    Republic of Azerbaijan  Economic management
1045    1    Macedonia, former Yugoslav Republic of  Economic management
647     1          Lao People's Democratic Republic  Economic management
1024    1               United Republic of Tanzania  Economic management
1010    1          Republic of the Union of Myanmar  Economic management
88      1                    Republic of Seychelles  Economic management
1437    1                     Republic of Guatemala  Economic management
223     1                    Republic of Mozambique  Economic management
...   ...                                       ...                  ...
844     8               Republic of the Philippines    Human development
1428    9                     Republic of Indonesia    Urban development
1426    9              Islamic Republic of Pakistan    Urban development
183     9                        Kingdom of Morocco    Urban development
194     9                              Burkina Faso    Urban development
200     9                    Republic of Mozambique    Urban development
1347    9           People's Republic of Bangladesh    Urban development
1342    9                                    Africa    Urban development
1318    9                                     Nepal    Urban development
1303    9            Plurinational State of Bolivia    Urban development
1290    9               United Republic of Tanzania    Urban development
318     9                         Republic of Benin    Urban development
333     9                People's Republic of China    Urban development
341     9                      Republic of Honduras    Urban development
354     9            Islamic Republic of Mauritania    Urban development
369     9             Federative Republic of Brazil    Urban development
414     9                         Republic of Ghana    Urban development
447     9                          Republic of Togo    Urban development
460     9             Socialist Republic of Vietnam    Urban development
1470    9  The Independent State of Papua New Guine    Urban development
1166    9                        West Bank and Gaza    Urban development
1104    9                      Republic of Colombia    Urban development
570     9                         Republic of India    Urban development
597     9          Democratic Republic of the Congo    Urban development
962     9              Middle East and North Africa    Urban development
737     9                        Republic of Uganda    Urban development
739     9                   Republic of South Sudan    Urban development
930     9                        Republic of Rwanda    Urban development
1495    9                         Republic of Kenya    Urban development
917     9                       Kingdom of Thailand    Urban development

[610 rows x 3 columns]

**10 major project themes**

In [179]:
mjt.name.value_counts().head(10)

Environment and natural resources management    250
Rural development                               216
Human development                               210
Public sector governance                        199
Social protection and risk management           168
Financial and private sector development        146
Social dev/gender/inclusion                     130
Trade and integration                            77
Urban development                                50
Economic management                              38
dtype: int64